SConscript ("bs_bos_core_base/SConscript.bs")
SConscript ("bs_matrix/SConscript.bs")
SConscript ("bs_base_linear_solvers/SConscript.bs")
SConscript ("bs_csr_ilu_prec/SConscript.bs")
SConscript ("bs_bos_core_data_storage/SConscript.bs")
SConscript ("bs_mesh/SConscript.bs")
SConscript ("bs_scal/SConscript.bs")
SConscript ("bs_pvt/SConscript.bs")
SConscript ("bs_bos_core/SConscript.bs")
SConscript ("hdf5_storage/SConscript")
SConscript ("common_types/SConscript.bs")

