release :
	scons -u kernel bs_bos_core_base bs_bos_core_data_storage bs_hdf5_storage \
	         bs_pvt bs_scal bs_mtx bspy_loader bs_mesh bs_bos_core \
	         bs_swift bs_lsolvers common_types bs_cpr_prec sql_well -j 4
#	scons -u kernel bs_bos_core_base bs_mtx bspy_loader bs_swift bs_lsolvers common_types bs_cpr_prec hdm_fluid -j 4
